language: r
dist: xenial
latex: false

branches:
  only:
  - master

cache:
  packages: yes

directories:
  - $HOME/bin

script:
- Rscript -e 'install.packages(c("devtools","aqp","soilDB","sharpshootR"))'
- Rscript -e 'devtools::install_github("ncss-tech/aqp", dependencies=FALSE)'
- Rscript -e 'devtools::install_github("ncss-tech/soilDB", dependencies=FALSE)'
- Rscript -e 'devtools::install_github("ncss-tech/sharpshootR", dependencies=FALSE)'
- Rscript -e 'blogdown::install_hugo()'
- Rscript -e 'blogdown::build_site()'

deploy:
  provider: pages
  skip_cleanup: TRUE
  github_token: $GITHUB_TOKEN
  keep_history: TRUE
  on:
    branch: master
  local_dir: public
  repo: brownag/brownag.github.io
  target_branch: master
  verbose: TRUE
  deployment_file: TRUE
