language: r
dist: xenial
latex: false

branches:
  only:
  - master

cache:
  packages: yes

directories:
  - $HOME/bin

before_install:
 - wget https://julialang-s3.julialang.org/bin/linux/x64/1.5/julia-1.5-latest-linux-x86_64.tar.gz
 - tar -xzf julia-1.5-latest-linux-x86_64.tar.gz
 - cp -r "$(find "." -maxdepth 2 -name "julia*" -type d | head -n 1)" "$HOME/julia"
 - export PATH="$HOME/julia/bin:$PATH"
 - export R_LD_LIBRARY_PATH="$(R RHOME)/lib:$HOME/julia/lib/julia"
 - Rscript -e 'install.packages(c("devtools","blogdown","JuliaCall","aqp","soilDB","sharpshootR"))'
 - Rscript -e 'devtools::install_github(c("ncss-tech/aqp", "ncss-tech/soilDB", "ncss-tech/sharpshootR"), dependencies=FALSE)'
 - wget https://github.com/gohugoio/hugo/releases/download/v0.76.5/hugo_0.76.5_Linux-64bit.tar.gz
 - tar -xzf hugo_0.76.5_Linux-64bit.tar.gz
 - cp -r "$(find "." -maxdepth 2 -name "hugo*" -type d | head -n 1)" "$HOME/hugo"
 - export PATH="$HOME/hugo:$PATH"

script:
 - Rscript -e 'if(!blogdown::hugo_available()) blogdown::install_hugo()'
 - Rscript -e 'blogdown::build_site()'

deploy:
  provider: pages
  skip_cleanup: TRUE
  github_token: GITHUB_TOKEN
  keep_history: TRUE
  on:
    branch: master
  local_dir: public
  repo: brownag/brownag.github.io
  target_branch: master
  verbose: TRUE
  deployment_file: TRUE
