baseurl = "/"
languageCode = "en-us"
title = "humus.rocks - soil is life on the rocks"
theme = "hugo-xmin-brownag"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "A blogdown website using R + Hugo"
    footer = "Andrew G. Brown ([humus.rocks](https://humus.rocks) | [GitHub](https://github.com/brownag) | [Twitter](https://twitter.com/humus_rocks)) \n\n [XMin Theme by Yihui Xie](https://github.com/yihui/hugo-xmin)"
